# Generated by Django 4.0.3 on 2022-10-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('Date_of_appointment', models.DateField()),
                ('Docname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('bloodgroup', models.CharField(max_length=200)),
                ('no_of_units_available', models.IntegerField(default=0)),
                ('contact', models.IntegerField(default=0)),
                ('email', models.EmailField(default='govardhansathvik83@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('hospitalname', models.CharField(max_length=200)),
                ('fee', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('email', models.EmailField(default='yellumahanthysaipavan@gmail.com', max_length=254)),
            ],
        ),
    ]
